# application.yml

spring:
  application:
    name: car-mats-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:when-authorized}
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}

security:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:86400000} # 24 hours
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000} # 7 days

admin:
  initial:
    email: ${ADMIN_INITIAL_EMAIL:admin@carmats.local}
    password: ${ADMIN_INITIAL_PASSWORD:}
    first-name: ${ADMIN_INITIAL_FIRST_NAME:Admin}
    last-name: ${ADMIN_INITIAL_LAST_NAME:Sistem}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%15.15t] [%X{requestId:-}] %-40.40logger{39} : %m%n"